### ISSUE TITLE
Able to connect but no Internet

### ISSUE THREAD

**Issue by npatel007** [naazf/docker-adguard-unbound-wireguard#1]
I am able to connect server hosted on OCI but not getting any internet on the Client

**Comment by oschmidteu** [comment]
Thats because you have to go through the AdGuard install process:
```
adguard      | 2021/10/15 09:06:30.083408 [info] This is the first launch of AdGuard Home, redirecting everything to /install.html 
adguard      | 2021/10/15 09:06:30.083450 [info] AdGuard Home is available on the following addresses:
adguard      | 2021/10/15 09:06:30.083604 [info] Go to http://127.0.0.1:3000
adguard      | 2021/10/15 09:06:30.083609 [info] Go to http://10.2.0.100:3000
```

I had the same "issue" after connecting via wireguard and setting up everything via http://10.2.0.100:3000 it was working.

The only issue is that as stated: 

> adguard      | 2021/10/15 09:06:30.083408 [info] This is the first launch of AdGuard Home, **redirecting everything to /install.html** 

Every request should have pointed to the install.html page which in fact was not the case.
